PUT http://localhost:8080/address
Accept: application/json
Content-Type: application/json

{
  "addresId": 1,
  "number": 123,
  "street": "Aspia",
  "zone": "Sopoc",
  "city": "La Paz",
  "country": "Bolivian"
}

###


GET http://localhost:8080/address/2
Accept: application/json

###