GET http://localhost:8080/admin/1
Accept: application/json

###

PUT http://localhost:8080/admin/updatepassword
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "oldPassword": "abc123456",
  "newPassword": "abc12345"
}

###

PUT http://localhost:8080/admin
Accept: application/json
Content-Type: application/json

{
  "adminId": 1,
  "firstName": "Andres",
  "firstSurname": "Palma",
  "secondSurname": "Gimenez",
  "ci": "1236884 LP",
  "phone": "+591 62954637",
  "email": "andres@gmail.com",
  "userName": "andre123"
}

###


