POST http://localhost:8080/bankAccount
Accept: application/json
Content-Type: application/json

{
  "pharmacyId": 3,
  "accountNumber": 123894,
  "bank": "Banco Union",
  "accountType": "Caja de Ahorros"
}

###

PUT http://localhost:8080/bankAccount
Accept: application/json
Content-Type: application/json

{
  "bankAccountId": 1,
  "accountNumber": 11111,
  "bank": "Banco Mercantil",
  "accountType": "Ahorro"
}

###

GET http://localhost:8080/bankAccount/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE2NjAxMzc2LCJleHAiOjE2MTY2MzczNzZ9.WKQ7nIFYhH0duU6Q0N0bmuIRPSc1LR1p5_L1-J1W-wo

