POST http://localhost:8080/brand
Accept: application/json
Content-Type: application/json


{
  "name": "Farmacias Inti",
  "phone": "+591 2495681",
  "email": "inti@gmail.com"
}

###


PUT http://localhost:8080/brand
Accept: application/json
Content-Type: application/json

{
  "brandId": 2,
  "name": "Laboratorios In",
  "phone": "+591 2645987",
  "email": "labinti@gmail.com"
}

###

DELETE http://localhost:8080/brand/1
Accept: application/json

###

GET http://localhost:8080/brand
Accept: application/json
Access-Control-Allow-Headers:

###

GET http://localhost:8080/brand/2
Accept: application/json

###
