POST http://localhost:8080/brand
Accept: application/json
Content-Type: application/json

{
  "name": "Laboratorios Sanofi",
  "phone": "+591 2965741",
  "email": "sanofi@email.com"
}

###


PUT http://localhost:8080/brand
Accept: application/json
Content-Type: application/json

{
  "brandId": 1,
  "name": "Laboratorios Vita",
  "phone": "+591 2522222",
  "email": "vita@email.com"
}

###

DELETE http://localhost:8080/brand/1
Accept: application/json

###

GET http://localhost:8080/brand
Accept: application/json

###

GET http://localhost:8080/brand/2
Accept: application/json

###
