POST http://localhost:8080/card
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE3MDY5NzA0LCJleHAiOjE2MTcxMDU3MDR9.vM8HFY7s_1MX1xXV8J68l5djyeDw6FV40GWxEdmLoOA

{
  "clientId": 1,
  "accountNumber": "132423523",
  "bank": "Banco Fie",
  "typeAccount": "Caja de ahorro",
  "cvvCode": "591",
  "month": "3",
  "year": "2022"
}

###


DELETE http://localhost:8080/card/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjE2ODk4Njk4LCJleHAiOjE2MTY5MzQ2OTh9.1NMbwtvaNWFLy4ZWODd5FmpERWKeRGZtxc84mCHL8JQ

###


