POST http://localhost:8080/card
Accept: application/json
Content-Type: application/json

{
  "clientId": 1,
  "accountNumber": "132423523",
  "bank": "Banco Fie",
  "typeAccount": "Caja de ahorro",
  "cvvCode": "591",
  "month": "3",
  "year": "2022"
}

###

PUT http://localhost:8080/card
Accept: application/json
Content-Type: application/json

{
  "cardId": 1,
  "accountNumber": "17877878873",
  "bank": "Banco Fie",
  "typeAccount": "Caja de ahorro",
  "cvvCode": "591",
  "month": "3",
  "year": "2023"
}

###


DELETE http://localhost:8080/card/1
Accept: application/json

###


