POST http://localhost:8080/client
Accept: application/json
Content-Type: application/json

{
  "firstName": "Marco",
  "firstSurname": "Orellana",
  "secondSurname": "Paz",
  "ci": "12345678 LP",
  "phone": "+591 2646791",
  "email": "marco@gmail.com",
  "userName": "marco123",
  "password": "marco123",
  "birthdate": "1997-03-11",
  "number": "516 B",
  "street": "14 de Septiembre",
  "zone": "Obrajes",
  "city": "La Paz",
  "country": "Bolivia"
}

###

PUT http://localhost:8080/client
Accept: application/json
Content-Type: application/json


{
  "clientId": 1,
  "firstName": "Erwin",
  "firstSurname": "Alejo",
  "secondSurname": "Colque",
  "ci": "12477775 LP",
  "phone": "+591 77777712",
  "email": "erwin@gmail.com",
  "userName": "erwinAle",
  "password": "er12343",
  "birthdate": "1999-11-02",
  "number": "1",
  "street": "14 de Septiembr",
  "zone": "Obrajes",
  "city": "La Paz",
  "country": "Bolivia"
}


###


DELETE http://localhost:8080/client/1
Accept: application/json


###

GET http://localhost:8080/client/1
Accept: application/json


###

GET http://localhost:8080/client?page=0&size=2&order=id&asc=true
Accept: application/json

###

GET http://localhost:8080/client/1/address
Accept: application/json

###


GET http://localhost:8080/client/1/card
Accept: application/json

###

GET http://localhost:8080/client/total
Accept: application/json

###


PUT http://localhost:8080/client/updatepassword
Accept: application/json
Content-Type: application/json

{
  "id": 2,
  "oldPassword": "abc123456",
  "newPassword": "abc12345"
}

###


GET http://localhost:8080/client/?user=admin&password=12345&type=Admin
Accept: application/json
Content-Type: application/json

###
