POST http://localhost:8080/client
Accept: application/json
Content-Type: application/json

{
  "firstName": "Juan Pablo",
  "firstSurname": "Melandre",
  "secondSurname": "Choquevolqueta",
  "ci": "158165779 LP",
  "phone": "+591 2645897",
  "email": "juan@gmail.com",
  "userName": "juan123",
  "password": "juan123",
  "birthdate": "1995-03-11",
  "number": "12",
  "street": "14 de Septiembre",
  "zone": "Obrajes",
  "city": "La Paz",
  "country": "Bolivia"
}

###

PUT http://localhost:8080/client
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE2ODg1ODQwLCJleHAiOjE2MTY5MjE4NDB9.e5HQuyTGXnClUBYDv4o_Kq8Oq-Sz71-_nbWSEN2WjlQ

{
  "clientId": 1,
  "firstName": "Erwin",
  "firstSurname": "Alejo",
  "secondSurname": "Colque",
  "ci": "12477775 LP",
  "phone": "+591 77777712",
  "email": "erwin@gmail.com",
  "userName": "erwinAle",
  "password": "er1234",
  "birthdate": "1999-11-02",
  "number": "1",
  "street": "14 de Septiembr",
  "zone": "Obrajes",
  "city": "La Paz",
  "country": "Bolivia"
}


###


DELETE http://localhost:8080/client/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE2ODg1ODQwLCJleHAiOjE2MTY5MjE4NDB9.e5HQuyTGXnClUBYDv4o_Kq8Oq-Sz71-_nbWSEN2WjlQ


###