GET http://localhost:8080/v1/contact
Accept: application/json

###

POST http://localhost:8080/v1/contact
Accept: application/json
Content-Type: application/json

{
 "firstName": "Juan",
 "firstSurname": "Perez"
}
