POST http://localhost:8080/payment
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJqdWFucGVyZXpAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwNjEwODEzLCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6ImJkYzRjYTU3LTliNWYtNDY3My05MWRiLWQxZTc2N2JkYzljYSIsImVtYWlsIjoianVhbnBlcmV6QGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.gfJndd6OOWIomR-lxtsccB-JapGb9RchRS0Sj0Wt-Z8

{
  "clientId": 1,
  "cardId": 1,
  "total": 20
}

###