POST http://localhost:8080/pharmacy
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE3MTI1NTQ0LCJleHAiOjE2MTcxNjE1NDR9.ecpyHvvgC1FC2W84oJXeyOZOkoXcX4m3mymREzZdKf8


{
  "name": "Farmacias Chave",
  "phone": "+591 24651835",
  "email": "farmacia-chavez@gmail.com"
}

###

PUT http://localhost:8080/pharmacy
Accept: application/json
Content-Type: application/json

{
  "pharmacyId": 1,
  "name": "Farmacias Juanes",
  "phone": "+591 2469351",
  "email": "farmacia-Boli@gmail.com"
}

###

DELETE http://localhost:8080/pharmacy/1
Accept: application/json

###

GET http://localhost:8080/pharmacy
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE3MTI1NTQ0LCJleHAiOjE2MTcxNjE1NDR9.ecpyHvvgC1FC2W84oJXeyOZOkoXcX4m3mymREzZdKf8

###

GET http://localhost:8080/pharmacy/11111
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjE2NTUyMDE2LCJleHAiOjE2MTY1ODgwMTZ9.eSF2MNufmS933XffR7N2duP1gzKAV9CDX3U0BBrlKEw

###

GET http://localhost:8080/pharmacy/4/bankAccount
Accept: application/json

###

GET http://localhost:8080/pharmacy/2/subsidiary
Accept: application/json

###

GET http://localhost:8080/pharmacy/2/admin
Accept: application/json

###