POST http://localhost:8080/pharmacy
Accept: application/json
Content-Type: application/json

{
  "name": "Farmacias Chavez",
  "phone": "+591 24651835",
  "email": "farmacia-chavez@gmail.com"
}

###

PUT http://localhost:8080/pharmacy
Accept: application/json
Content-Type: application/json

{
  "pharmacyId": 4,
  "name": "Farmacias Juanes",
  "phone": "+591 2469351",
  "email": "farmacia-Boli@gmail.com"
}

###

DELETE http://localhost:8080/pharmacy/3
Accept: application/json

###

GET http://localhost:8080/pharmacy
Accept: application/json

###

GET http://localhost:8080/pharmacy/4
Accept: application/json

###

GET http://localhost:8080/pharmacy/4/bankAccount
Accept: application/json

###

GET http://localhost:8080/pharmacy/2/subsidiary
Accept: application/json

###

GET http://localhost:8080/pharmacy/2/admin
Accept: application/json

###