POST http://localhost:8080/pharmacyAdmin
Accept: application/json
Content-Type: application/json

{
  "subsidiaryId": 1,
  "firstName": "Sergio",
  "firstSurname": "Lara",
  "secondSurname": "Vaca",
  "ci": "649835 LP",
  "phone": "+591 61984573",
  "email": "sergio@gmail.com",
  "userName": "SergioLara",
  "password": "abc12345"
}

###

PUT http://localhost:8080/pharmacyAdmin
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoxLCJ1c2VyX25hbWUiOiJhbmRyZXNAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImFkbWluSWQiOjEsImV4cCI6MTYxOTQxOTQ3MywidXNlck5hbWUiOiJhbmRyZWNpdG8iLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImVmZTcxNDdiLWU0NjEtNDEyOC05NzRiLTU4ZWFiM2JlNzc0ZiIsImVtYWlsIjoiYW5kcmVzQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIn0.4Lcml83YeeRi5jlcNNNBjkSx29nnQmm_kIDb2gK1n3Q

{
  "pharmacyAdminId": 1,
  "subsidiaryId": 1,
  "firstName": "Jose",
  "firstSurname": "Perez",
  "secondSurname": "Luan",
  "ci": "12459635 LP",
  "phone": "+591 78596312",
  "email": "juanperez@gmail.com",
  "userName": "JuanitoAlcachofa"
}

###

DELETE http://localhost:8080/pharmacyAdmin/3
Accept: application/json

###

GET http://localhost:8080/pharmacyAdmin/2
Accept: application/json

###


PUT http://localhost:8080/pharmacyAdmin/updatepassword
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoxLCJ1c2VyX25hbWUiOiJhbmRyZXNAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImFkbWluSWQiOjEsImV4cCI6MTYxOTQyMDY4MiwidXNlck5hbWUiOiJhbmRyZWNpdG8iLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6IjBhMjYyZDA1LTdkNjctNDI4OS1iM2Q2LTFmYmM1ZDBiNWY3NiIsImVtYWlsIjoiYW5kcmVzQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIn0.TEI843YDCDidbfMlEotxOGGx84AE7noiTRgNZQspUR4

{
  "id": 1,
  "oldPassword": "abc123456",
  "newPassword": "abc12345"
}

###