POST http://localhost:8080/pharmacyAdmin
Accept: application/json
Content-Type: application/json

{
  "subsidiaryId": 4,
  "firstName": "Sergio",
  "firstSurname": "Lara",
  "secondSurname": "Vaca",
  "ci": "649835 LP",
  "phone": "+591 61984573",
  "email": "sergio@gmail.com",
  "userName": "SergioLara",
  "password": "abc12345"
}