POST http://localhost:8080/product
Accept: application/json
Content-Type: application/json

{
  "subsidiaryId": 2,
  "brandId": 2,
  "name": "Paracetamol",
  "stock": "400",
  "price": "0.10",
  "type": "Tableta",
  "dose": "200 gr",
  "description": "Calmante, utilizado para todo tipo de dolor"
}

###

PUT http://localhost:8080/product
Accept: application/json
Content-Type: application/json

{
  "productId": 1,
  "subsidiaryId": 1,
  "brandId": 1,
  "name": "Paracetamol",
  "stock": "250",
  "price": "0.50",
  "type": "tableta",
  "dose": "200 ml gr",
  "description": "Calmante, utilizado para todo tipo de dolor y apto para todas las personas"
}

###


DELETE http://localhost:8080/product/2
Accept: application/json

###

GET http://localhost:8080/product/2
Accept: application/json

###

GET http://localhost:8080/product/2/list?page=0&size=5&order=name&asc=false&price=50.0
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoxLCJ1c2VyX25hbWUiOiJhbmRyZXNAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImFkbWluSWQiOjEsImV4cCI6MTYxODM5MjgzMCwidXNlck5hbWUiOiJhbmRyZWNpdG8iLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImJhODg3OTk3LTIxNWQtNDdmYS05OWU1LTBlYjExNmFlMGEzZiIsImVtYWlsIjoiYW5kcmVzQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIn0.ohPVfffig-raK3qnRocbR2OJc-mKlPVOS7m9FbZadD4

###

GET http://localhost:8080/product/1/total
Accept: application/json

###