POST http://localhost:8080/product
Accept: application/json
Content-Type: application/json

{
  "subsidiaryId": 1,
  "brandId": 1,
  "doseTypeId": 1,
  "name": "Ibuprofeno",
  "stock": "400",
  "price": "0.10",
  "type": "Tableta",
  "dose": "200",
  "description": "Calmante, utilizado para todo tipo de dolor"
}

###

PUT http://localhost:8080/product
Accept: application/json
Content-Type: application/json

{
  "productId": 1,
  "subsidiaryId": 1,
  "brandId": 1,
  "doseTypeId": 1,
  "name": "Paracetamol",
  "stock": "250",
  "price": "0.50",
  "type": "tableta",
  "dose": "200",
  "description": "Calmante, utilizado para todo tipo de dolor y apto para todas las personas"
}

###


DELETE http://localhost:8080/product/2
Accept: application/json


###

GET http://localhost:8080/product/24
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJlcndpbjFAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwMTM1NDc2LCJ1c2VyTmFtZSI6ImFicmlzbGFuMCIsImF1dGhvcml0aWVzIjpbIlJPTEVfUEhBUk1BQ1lfQURNSU4iXSwianRpIjoiYzkzYTUwOTEtZTkzZC00YjJkLTg5YmEtYjEwNjU3ODA5NjM0IiwiZW1haWwiOiJlcndpbjFAZ21haWwuY29tIiwiY2xpZW50X2lkIjoibWVkaWNodWJhcHAiLCJwaGFybUFkbWluSWQiOjF9.BLWaert5ezmGlMo5g3uw4B27tQP5uT1Xist0sJULwdw

###

#GET http://localhost:8080/product/1/list?page=0&size=5&order=name&asc=false&value=50.0&typevalue=price
GET http://localhost:8080/product/1/list?page=0&size=5&asc=true&value=&typevalue=all
Accept: application/json

###

GET http://localhost:8080/product/1/total
Accept: application/json

###