POST http://localhost:8080/purchase
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoxLCJ1c2VyX25hbWUiOiJhbmRyZXNAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImFkbWluSWQiOjEsImV4cCI6MTYyMDM5MjQwMywidXNlck5hbWUiOiJhbmRyZWNpdG8iLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImUxNTM1MjExLWI5MGQtNDA1ZC05M2VkLTZlNTAxNDE1YjQ2NyIsImVtYWlsIjoiYW5kcmVzQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIn0.-lLkQhyMUF1q7Be3MAWV296m4Dwqt3wZLC9JujC-RLU

{
  "totalAmount": 10,
  "firstSurname": "Velasco",
  "nit": "124578596 LP",
  "products": [
    {
      "productId": 1,
      "quantity": 16
    },
    {
      "productId": 2,
      "quantity": 20
    }
  ]
}

###


GET http://localhost:8080/purchase/1/list?page=0&size=5
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJlcndpbjFAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwOTA3MzA0LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6ImNkYmRkMzYwLTYzZDgtNGU4Ni05Y2Q0LTYzNjIyNTc2NDk3ZSIsImVtYWlsIjoiZXJ3aW4xQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.WdhrDTrsOPLIzXtI0oMP3uYkw3X1VA9zRWtpdEwC-AQ

###


GET http://localhost:8080/purchase/1/subsidiary/report?page=0&size=5&asc=false
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJlcndpbjFAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwOTA3MzA0LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6ImNkYmRkMzYwLTYzZDgtNGU4Ni05Y2Q0LTYzNjIyNTc2NDk3ZSIsImVtYWlsIjoiZXJ3aW4xQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.WdhrDTrsOPLIzXtI0oMP3uYkw3X1VA9zRWtpdEwC-AQ

###


GET http://localhost:8080/purchase/1/subsidiary/report/general?page=0&size=5&asc=false
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJlcndpbjFAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwOTA3MzA0LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6ImNkYmRkMzYwLTYzZDgtNGU4Ni05Y2Q0LTYzNjIyNTc2NDk3ZSIsImVtYWlsIjoiZXJ3aW4xQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.WdhrDTrsOPLIzXtI0oMP3uYkw3X1VA9zRWtpdEwC-AQ

###