POST http://localhost:8080/purchase
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJqdWFucGVyZXpAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwOTUxNzM0LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6IjI0NDhkZDA1LTY1NTEtNDI0OS04ZjkwLTJmZDhjNzI4NjBlZCIsImVtYWlsIjoianVhbnBlcmV6QGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.gyLNm64w7oH4AWZmlCgE6Pi2EhQHQqydM7q2sTovxOk

{
  "totalAmount": 15,
  "firstSurname": "Velasco",
  "nit": "124578596 LP",
  "products": [
    {
      "productId": 1,
      "quantity": 16
    },
    {
      "productId": 2,
      "quantity": 20
    }
  ]
}

###


GET http://localhost:8080/purchase/1/list?page=0&size=5
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJqdWFucGVyZXpAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwOTUxNzM0LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6IjI0NDhkZDA1LTY1NTEtNDI0OS04ZjkwLTJmZDhjNzI4NjBlZCIsImVtYWlsIjoianVhbnBlcmV6QGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.gyLNm64w7oH4AWZmlCgE6Pi2EhQHQqydM7q2sTovxOk

###

GET http://localhost:8080/purchase/1/graph?init=2020-01-01&end=2021-05-14
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJqdWFucGVyZXpAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwOTUxNzM0LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6IjI0NDhkZDA1LTY1NTEtNDI0OS04ZjkwLTJmZDhjNzI4NjBlZCIsImVtYWlsIjoianVhbnBlcmV6QGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.gyLNm64w7oH4AWZmlCgE6Pi2EhQHQqydM7q2sTovxOk

###


GET http://localhost:8080/purchase/1/subsidiary/report?page=0&size=5&asc=false
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJlcndpbjFAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwOTYyODY4LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6IjQwNmQyZWE5LTk2ZTAtNGIwYy1hOTc0LWVmNDhlNDhkOTQ3ZSIsImVtYWlsIjoiZXJ3aW4xQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.h-wOMAkbUetENAzV8SnTZ5oIyPTNJ2uOHcv3kCfav3I

###


GET http://localhost:8080/purchase/1/subsidiary/report/general?page=0&size=5&asc=false
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJlcndpbjFAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwOTA3MzA0LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6ImNkYmRkMzYwLTYzZDgtNGU4Ni05Y2Q0LTYzNjIyNTc2NDk3ZSIsImVtYWlsIjoiZXJ3aW4xQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.WdhrDTrsOPLIzXtI0oMP3uYkw3X1VA9zRWtpdEwC-AQ

###

GET http://localhost:8080/purchase/1/subsidiary/report/statistics
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJlcndpbjFAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwOTYyODY4LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6IjQwNmQyZWE5LTk2ZTAtNGIwYy1hOTc0LWVmNDhlNDhkOTQ3ZSIsImVtYWlsIjoiZXJ3aW4xQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.h-wOMAkbUetENAzV8SnTZ5oIyPTNJ2uOHcv3kCfav3I

###

