POST http://localhost:8080/reserve
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJqdWFucGVyZXpAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwMzgxNjk0LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6IjU1YjVkYjZhLTIxODgtNGVjYy05ODliLWFlMDVhZTgyYTIyOSIsImVtYWlsIjoianVhbnBlcmV6QGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.fJffCfquZNe3pVVMGaNLh6v7kSlpuppzW822ZaknEDA

{
  "clientId": 1,
  "productId": 2,
  "quantity": 15
}

###

GET http://localhost:8080/reserve?page=0&size=5&state=2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoxLCJ1c2VyX25hbWUiOiJhbmRyZXNAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImFkbWluSWQiOjEsImV4cCI6MTYyMDM5MjQwMywidXNlck5hbWUiOiJhbmRyZWNpdG8iLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImUxNTM1MjExLWI5MGQtNDA1ZC05M2VkLTZlNTAxNDE1YjQ2NyIsImVtYWlsIjoiYW5kcmVzQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIn0.-lLkQhyMUF1q7Be3MAWV296m4Dwqt3wZLC9JujC-RLU

###


GET http://localhost:8080/reserve/1/list?page=0&size=5&state=2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoxLCJ1c2VyX25hbWUiOiJhbmRyZXNAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImFkbWluSWQiOjEsImV4cCI6MTYyMDM5MjQwMywidXNlck5hbWUiOiJhbmRyZWNpdG8iLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6ImUxNTM1MjExLWI5MGQtNDA1ZC05M2VkLTZlNTAxNDE1YjQ2NyIsImVtYWlsIjoiYW5kcmVzQGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIn0.-lLkQhyMUF1q7Be3MAWV296m4Dwqt3wZLC9JujC-RLU

###


GET http://localhost:8080/reserve/501/quantity?state=1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6NTAxLCJyb2xlIjozLCJ1c2VyX25hbWUiOiJqdWFuam9AZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImV4cCI6MTYyMDQ2MjQ2NiwidXNlck5hbWUiOiJqdWFuam9GRF8xOTk5IiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DTElFTlQiXSwianRpIjoiMGUxMjQ1ZTYtOWM3Yy00NWE0LWI2NjYtYjIyZTY3NWIyMDExIiwiZW1haWwiOiJqdWFuam9AZ21haWwuY29tIiwiY2xpZW50X2lkIjoibWVkaWNodWJhcHAifQ.CeF3GZRTMcYM0x-FHmgeBx1CQej_dOWIzp6ZZjza_gg

###


GET http://localhost:8080/reserve/501/total?state=1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6NTAxLCJyb2xlIjozLCJ1c2VyX25hbWUiOiJqdWFuam9AZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImV4cCI6MTYyMDQ2MjQ2NiwidXNlck5hbWUiOiJqdWFuam9GRF8xOTk5IiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9DTElFTlQiXSwianRpIjoiMGUxMjQ1ZTYtOWM3Yy00NWE0LWI2NjYtYjIyZTY3NWIyMDExIiwiZW1haWwiOiJqdWFuam9AZ21haWwuY29tIiwiY2xpZW50X2lkIjoibWVkaWNodWJhcHAifQ.CeF3GZRTMcYM0x-FHmgeBx1CQej_dOWIzp6ZZjza_gg

###

