GET http://localhost:8080/reserve?page=0&size=5&state=2
Accept: application/json

###

POST http://localhost:8080/reserve
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoyLCJ1c2VyX25hbWUiOiJqdWFucGVyZXpAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sInN1YnNpZGlhcnlJZCI6MSwiZXhwIjoxNjIwMzgxNjk0LCJ1c2VyTmFtZSI6Ikp1YW5pdG9BbGNhY2hvZmEiLCJhdXRob3JpdGllcyI6WyJST0xFX1BIQVJNQUNZX0FETUlOIl0sImp0aSI6IjU1YjVkYjZhLTIxODgtNGVjYy05ODliLWFlMDVhZTgyYTIyOSIsImVtYWlsIjoianVhbnBlcmV6QGdtYWlsLmNvbSIsImNsaWVudF9pZCI6Im1lZGljaHViYXBwIiwicGhhcm1BZG1pbklkIjoxfQ.fJffCfquZNe3pVVMGaNLh6v7kSlpuppzW822ZaknEDA

{
  "clientId": 1,
  "productId": 2,
  "quantity": 20
}