POST http://localhost:8080/subsidiary
Accept: application/json
Content-Type: application/json

{
  "pharmacyId": 2,
  "subsidiaryName": "Farmacias Chavez - Sopocachi",
  "phone": "+591 24981657",
  "email": "farmaCha-Sopocachi@gmail.com",
  "number": "158",
  "street": "Mariscal Santa Cruz",
  "zone": "El Prado",
  "city": "La Paz",
  "country": "Bolivia"
}