POST http://localhost:8080/subsidiary
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE2NjAxMzc2LCJleHAiOjE2MTY2MzczNzZ9.WKQ7nIFYhH0duU6Q0N0bmuIRPSc1LR1p5_L1-J1W-wo

{
  "pharmacyId": 1,
  "subsidiaryName": "Farmacias Chavez - Arce",
  "phone": "+591 24981657",
  "email": "farmaCha-Sopocachi@gmail.com",
  "number": "158",
  "street": "Aspiazu",
  "zone": "Sopocachi",
  "city": "La Paz",
  "country": "Bolivia"
}

###


PUT http://localhost:8080/subsidiary
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE2NjAxMzc2LCJleHAiOjE2MTY2MzczNzZ9.WKQ7nIFYhH0duU6Q0N0bmuIRPSc1LR1p5_L1-J1W-wo


{
  "subsidiaryId": 2,
  "subsidiaryName": "Farmacias Chavez - Asc",
  "phone": "+591 24982333",
  "email": "farmaCha-Sopocachi@gmail.com",
  "number": "154",
  "street": "Aspiazu",
  "zone": "Sopocachi",
  "city": "La Pazz",
  "country": "Bolivia"
}

###

DELETE http://localhost:8080/subsidiary/1
Accept: application/json

###

GET http://localhost:8080/subsidiary/4
Accept: application/json

###

GET http://localhost:8080/subsidiary/1/product
Accept: application/json

###

GET http://localhost:8080/subsidiary/4/admin
Accept: application/json

###