POST http://localhost:8080/subsidiary
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE2NjA3MDk0LCJleHAiOjE2MTY2NDMwOTR9.zxIxABn1RJ3bv-CosN0MxBjQ3_olLPGgUneimc5UJqc


{
  "pharmacyId": 1,
  "subsidiaryName": "Farmacias Chavez - Sopocachi",
  "phone": "+591 24981657",
  "email": "farmaCha-Sopocachi@gmail.com",
  "number": "158",
  "street": "Aspiazu",
  "zone": "Sopocachi",
  "city": "La Paz",
  "country": "Bolivia"
}

###


PUT http://localhost:8080/subsidiary
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE2NjA3MDk0LCJleHAiOjE2MTY2NDMwOTR9.zxIxABn1RJ3bv-CosN0MxBjQ3_olLPGgUneimc5UJqc


{
  "subsidiaryId": 2,
  "subsidiaryName": "Farmacias Chavez - so",
  "phone": "+591 24982333",
  "email": "farmaCha-Sopocachi@gmail.com",
  "number": "154",
  "street": "Aspiazu",
  "zone": "Arce",
  "city": "El Alto",
  "country": "Bolivia"
}

###

DELETE http://localhost:8080/subsidiary/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjE2NjA3MDk0LCJleHAiOjE2MTY2NDMwOTR9.zxIxABn1RJ3bv-CosN0MxBjQ3_olLPGgUneimc5UJqc

###

GET http://localhost:8080/subsidiary/4
Accept: application/json

###

GET http://localhost:8080/subsidiary/1/product
Accept: application/json

###

GET http://localhost:8080/subsidiary/4/admin
Accept: application/json

###